### ISSUE TITLE
For jason

### ISSUE THREAD

**Issue by MCUnderground** [LostTeam/SoundsAPI#2]
Wanna make sound api for all sounds?

**Comment by MCUnderground** [comment]
@jasonwynn10

**Comment by jasonwynn10** [comment]
sounds good to me XD

**Comment by MCUnderground** [comment]
U start it .-. Or just remake this and rename it and all.. I wonder if we can pull all sounds from mcpe

**Comment by jasonwynn10** [comment]
I might be able to have the user be able to import sounds from the console by checking if there is any file with .mp3 in the name.
